CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100),
  role VARCHAR(50)
);

CREATE TABLE Equipment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(100) IS NOT NULL,
  make VARCHAR(100) IS NOT NULL,
  model VARCHAR(100) IS NOT NULL,
  serial VARCHAR (100),
  tag VARCHAR (100),
  description VARCHAR(150),
  status VARCHAR(100) IS NOT NULL,
  room VARCHAR(100) IS NOT NULL,
  notes VARCHAR(100),
  expiration DATE VARCHAR(100)
);
